#!/bin/bash

set -o nounset
set -o errexit
 
# The base location from where to retrieve new versions of this script
UPDATE_BASE=https://hovergroup.googlecode.com/svn/trunk/ivp-extend/hover_update_actual

# Download new version
echo -n "Downloading latest version..."
if ! wget --quiet --output-document="hover_update_actual" $UPDATE_BASE ; then
    echo "Failed: Error while trying to wget new version!"
    echo "File requested: $UPDATE_BASE/$SELF"
    exit 1
fi
echo "Done."
